# Generated by Django 4.1.3 on 2022-12-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedb',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
