# Generated by Django 4.1.3 on 2022-12-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_login_alter_feedback_feedb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedb',
        ),
        migrations.AddField(
            model_name='feedback',
            name='city',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='desc',
            field=models.CharField(default='null', max_length=122),
        ),
    ]
