# Generated by Django 4.1.3 on 2022-12-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_feedback_address_remove_feedback_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
