# Generated by Django 4.1.3 on 2022-12-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_alter_login_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nd', models.IntegerField()),
                ('zsign', models.CharField(max_length=20)),
                ('sign', models.ImageField(upload_to='')),
            ],
        ),
    ]
