# Generated by Django 4.1.3 on 2022-12-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_report_nd_remove_report_sign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nakshatra', models.CharField(default='', max_length=20)),
                ('positive', models.TextField(default='', max_length=50)),
                ('negative', models.TextField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='firstname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='gender',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='lastname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='month',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.IntegerField(default=''),
        ),
    ]
