# Generated by Django 4.1.3 on 2022-12-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_traits_alter_report_date_alter_report_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traits',
            name='negative',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='traits',
            name='positive',
            field=models.TextField(default=''),
        ),
    ]
